import { expect, test } from "vitest";
import { decoded, encoded, translations } from "./main";
const convertedResult = [
  {
    groupId: 783,
    areaId: "",
    departmentId: "Маркетинг",
    directionId: "",
    mediaTypeId: "",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "",
    formatId: "",
    unitId: "Фикс",
    platformId: "",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: null,
    ca: null,
    mpmId: null,
  },
  {
    groupId: 784,
    areaId: "",
    departmentId: "Маркетинг",
    directionId: "",
    mediaTypeId: "",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "",
    formatId: "",
    unitId: "Фикс",
    platformId: "",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: null,
    ca: null,
    mpmId: null,
  },
  {
    groupId: 785,
    areaId: "",
    departmentId: "Маркетинг",
    directionId: "",
    mediaTypeId: "",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "",
    formatId: "",
    unitId: "Фикс",
    platformId: "",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: null,
    ca: null,
    mpmId: null,
  },
  {
    groupId: 786,
    areaId: "",
    departmentId: "Маркетинг",
    directionId: "",
    mediaTypeId: "",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "",
    formatId: "",
    unitId: "Фикс",
    platformId: "",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: null,
    ca: null,
    mpmId: null,
  },
  {
    groupId: 787,
    areaId: "",
    departmentId: "Маркетинг",
    directionId: "",
    mediaTypeId: "",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "",
    formatId: "",
    unitId: "Фикс",
    platformId: "",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: null,
    ca: null,
    mpmId: null,
  },
  {
    groupId: 788,
    areaId: "",
    departmentId: "Маркетинг",
    directionId: "СММ - 3",
    mediaTypeId: "СММ",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "СММ - 2",
    formatId: "",
    unitId: "Фикс",
    platformId: "",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: null,
    ca: null,
    mpmId: null,
  },
  {
    groupId: 789,
    areaId: "",
    departmentId: "Маркетинг",
    directionId: "СММ - 3",
    mediaTypeId: "СММ",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "Баннеры",
    formatId: "",
    unitId: "Фикс",
    platformId: "",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: null,
    ca: null,
    mpmId: null,
  },
  {
    groupId: 790,
    areaId: "",
    departmentId: "Маркетинг",
    directionId: "СММ - 3",
    mediaTypeId: "СММ",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "СММ - 2",
    formatId: "",
    unitId: "Фикс",
    platformId: "",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: null,
    ca: null,
    mpmId: null,
  },
  {
    groupId: 791,
    areaId: "",
    departmentId: "Маркетинг",
    directionId: "СММ - 3",
    mediaTypeId: "СММ",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "СММ - 2",
    formatId: "Статья",
    unitId: "Фикс",
    platformId: "145868",
    budgetId: null,
    adPlatformId: "Посевы",
    service: null,
    formatSize: "не применим",
    ca: null,
    mpmId: null,
  },
  {
    groupId: 792,
    areaId: "",
    departmentId: "Маркетинг",
    directionId: "СММ - 3",
    mediaTypeId: "СММ",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "СММ - 2",
    formatId: "Статья",
    unitId: "Фикс",
    platformId: "145868",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: "не применим",
    ca: null,
    mpmId: null,
  },
  {
    groupId: 793,
    areaId: "",
    departmentId: "Маркетинг",
    directionId: "СММ - 3",
    mediaTypeId: "СММ",
    mediaId: "Диджитал",
    resellingId: "Нет",
    serviceTypeId: "Размещение",
    formatTypeId: "Баннеры",
    formatId: "Баннеры",
    unitId: "Фикс",
    platformId: "",
    budgetId: null,
    adPlatformId: "Telegram",
    service: null,
    formatSize: "Не применимо",
    ca: null,
    mpmId: null,
  },
];
const numOfUniqueIds = Object.keys(translations).length;

test("check for consistency of the result", () => {
  expect(decoded(encoded, translations)).toStrictEqual(convertedResult);
});
